### ISSUE TITLE
Access not granted or expired. (line 363, file "Service", project "OAuth2")

### ISSUE THREAD

**Issue by tastanonur** [googlesamples/apps-script-oauth2#110] opened 2018-03-20 11:37 UTC
I am using your OAuth2 library. I try to reach from within google sheets to gmail settings with Gmail API. I connected for a google account successfully and i could change gmail settings. But i tried another google account but It always displays a connection issue. 

Application type: Web application
Given API rights: Gmail API, Admin SDK 
Authorised Redirect URIs: https://script.google.com/macros/d/{SCRIPT ID}/usercallback
OAuth account re-creates lots of time but it does not work. 
I calls the link from getRedirectUri(), it displays "Authorization is required to perform that action."

Please let me know that how can i solve problem. Whats is the difference between google accounts ? 

```
var CLIENT_ID = '----';
var CLIENT_SECRET = '----';

function getService() {
      // Create a new service with the given name. The name will be used when
      // persisting the authorized token, so ensure it is unique within the
      // scope of the property store.
      return OAuth2.createService('blogger')

      // Set the endpoint URLs, which are the same for all Google services.
      .setAuthorizationBaseUrl('https://accounts.google.com/o/oauth2/auth')
      .setTokenUrl('https://accounts.google.com/o/oauth2/token')

      // Set the client ID and secret, from the Google Developers Console.
      .setClientId(CLIENT_ID)
      .setClientSecret(CLIENT_SECRET)

      // Set the name of the callback function in the script referenced
      // above that should be invoked to complete the OAuth flow.
      .setCallbackFunction('authCallback')

      // Set the property store where authorized tokens should be persisted.
      .setPropertyStore(PropertiesService.getUserProperties())

      // Set the scopes to request (space-separated for Google services).
      // this is blogger read only scope for write access is:
      // https://www.googleapis.com/auth/blogger
      .setScope('https://www.googleapis.com/auth/gmail.settings.sharing')

      // Below are Google-specific OAuth2 parameters.

      // Sets the login hint, which will prevent the account chooser screen
      // from being shown to users logged in with multiple accounts.
      .setParam('login_hint', Session.getActiveUser().getEmail())
      
      // Requests offline access.
      .setParam('access_type', 'offline')

      // Forces the approval prompt every time. This is useful for testing,
      // but not desirable in a production application.
      .setParam('approval_prompt', 'force');
  var authorizationUrl = service.getAuthorizationUrl();
  Logger.log(authorizationUrl);
}

function reset() {
  getService().reset();
}

function logRedirectUri() {
  Logger.log(getService().getRedirectUri());
}

function clearService(){
  OAuth2.createService('bloggerService')
      .setPropertyStore(PropertiesService.getUserProperties())
      .reset();
}
```

**Comment by erickoledadevrel** [comment] 2018-03-23 13:41
This sounds like a duplicate of #107, please follow that issue.

**Closed by erickoledadevrel** 2018-03-23 13:41 UTC
